### ISSUE TITLE
Error: The process '/usr/bin/xvfb-run' failed with exit code 134

### ISSUE THREAD

**Issue by BigBigBIgMan** [BlueHtml/Note163Checkin#15]
我按着步骤操作，运行时报错了，代码如下
`Run coactions/setup-xvfb@main
/usr/bin/sudo apt-get install -y xvfb x11-xserver-utils
Reading package lists...
Building dependency tree...
Reading state information...
xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.1).
Suggested packages:
  nickle cairo-5c xorg-docs-core
The following NEW packages will be installed:
  x11-xserver-utils
0 upgraded, 1 newly installed, 0 to remove and 17 not upgraded.
Need to get 170 kB of archives.
After this operation, 581 kB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu jammy/main amd[6](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:7)4 x11-xserver-utils amd64 [7](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:8).7+9build1 [170 kB]
Fetched 170 kB in 0s (2330 kB/s)
Selecting previously unselected package x11-xserver-utils.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... [8](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:9)0%
(Reading database ... 85%
(Reading database ... [9](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:10)0%
(Reading database ... 95%
(Reading database ... [10](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:11)0%
(Reading database ... 222125 files and directories currently installed.)
Preparing to unpack .../x[11](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:12)-xserver-utils_7.7+9build1_amd64.deb ...
Unpacking x11-xserver-utils (7.7+9build1) ...
Setting up x11-xserver-utils (7.7+9build1) ...
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 5.15.0-1036-azure
NEEDRESTART-KEXP: 5.15.0-1036-azure
NEEDRESTART-KSTA: 1
Command: dotnet run
/usr/bin/xvfb-run --auto-servernum dotnet run
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'json')
   at System.Text.Json.ThrowHelper.ThrowArgumentNullException(String parameterName)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Program.<<Main>$>g__Deserialize|0_5[T](String json) in /home/runner/work/Note163Checkin/Note163Checkin/Program.cs:line 188
   at Program.<Main>$(String[] args) in /home/runner/work/Note163Checkin/Note163Checkin/Program.cs:line 8
   at Program.<Main>(String[] args)
/usr/bin/bash /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh
/usr/bin/bash: /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh: No such file or directory
Error: The process '/usr/bin/xvfb-run' failed with exit code [134](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:14)`

**Comment by BigBigBIgMan** [comment]
Run coactions/setup-xvfb@main
/usr/bin/sudo apt-get install -y xvfb x11-xserver-utils
Reading package lists...
Building dependency tree...
Reading state information...
xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.1).
Suggested packages:
  nickle cairo-5c xorg-docs-core
The following NEW packages will be installed:
  x11-xserver-utils
0 upgraded, 1 newly installed, 0 to remove and 17 not upgraded.
Need to get 170 kB of archives.
After this operation, 581 kB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu jammy/main amd[6](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:7)4 x11-xserver-utils amd64 [7](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:8).7+9build1 [170 kB]
Fetched 170 kB in 0s (2330 kB/s)
Selecting previously unselected package x11-xserver-utils.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... [8](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:9)0%
(Reading database ... 85%
(Reading database ... [9](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:10)0%
(Reading database ... 95%
(Reading database ... [10](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:11)0%
(Reading database ... 222125 files and directories currently installed.)
Preparing to unpack .../x[11](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:12)-xserver-utils_7.7+9build1_amd64.deb ...
Unpacking x11-xserver-utils (7.7+9build1) ...
Setting up x11-xserver-utils (7.7+9build1) ...
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 5.15.0-1036-azure
NEEDRESTART-KEXP: 5.15.0-1036-azure
NEEDRESTART-KSTA: 1
Command: dotnet run
/usr/bin/xvfb-run --auto-servernum dotnet run
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'json')
   at System.Text.Json.ThrowHelper.ThrowArgumentNullException(String parameterName)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Program.<<Main>$>g__Deserialize|0_5[T](String json) in /home/runner/work/Note163Checkin/Note163Checkin/Program.cs:line 188
   at Program.<Main>$(String[] args) in /home/runner/work/Note163Checkin/Note163Checkin/Program.cs:line 8
   at Program.<Main>(String[] args)
/usr/bin/bash /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh
/usr/bin/bash: /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh: No such file or directory
Error: The process '/usr/bin/xvfb-run' failed with exit code [13](https://github.com/BigBigBIgMan/Note163Checkin/actions/runs/4815744428/jobs/8574706266#step:3:14)4
