### ISSUE TITLE
cookie失效后，总是登录失败，有办法解决吗？

### ISSUE THREAD

**Issue by BigBigBIgMan** [BlueHtml/Note163Checkin#17]
cookie失效后，总是登录失败，有办法解决吗？

**Comment by StoneForests** [comment]
我也是，最近youdao是不是升级了，没法登录了，action日志如下：

```
Run coactions/setup-xvfb@main
/usr/bin/sudo apt-get install -y xvfb x11-xserver-utils
Reading package lists...
Building dependency tree...
Reading state information...
xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.1).
Suggested packages:
  nickle cairo-5c xorg-docs-core
The following NEW packages will be installed:
  x11-xserver-utils
0 upgraded, 1 newly installed, 0 to remove and 30 not upgraded.
Need to get 170 kB of archives.
After this operation, 581 kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu jammy/main amd[6](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:7)4 x11-xserver-utils amd64 [7](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:8).7+9build1 [170 kB]
Fetched 170 kB in 0s (1275 kB/s)
Selecting previously unselected package x11-xserver-utils.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... [8](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:9)0%
(Reading database ... 85%
(Reading database ... [9](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:10)0%
(Reading database ... 95%
(Reading database ... [10](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:11)0%
(Reading database ... 225746 files and directories currently installed.)
Preparing to unpack .../x[11](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:12)-xserver-utils_7.7+9build1_amd64.deb ...
Unpacking x11-xserver-utils (7.7+9build1) ...
Setting up x11-xserver-utils (7.7+9build1) ...
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 6.2.0-10[12](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:13)-azure
NEEDRESTART-KEXP: 6.2.0-1012-azure
NEEDRESTART-KSTA: 1
Command: dotnet run
/usr/bin/xvfb-run --auto-servernum dotnet run
redis:有效
有道云笔记签到开始运行...
共 1 个账号，正在运行账号 1: youdao github action ...
Login时出现异常！Evaluation failed: TypeError: Cannot read properties of null (reading 'querySelector')
    at main (__puppeteer_evaluation_script__:8:44)
    at __puppeteer_evaluation_script__:16:1.    at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 179
   at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line [14](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:15)6
   at PuppeteerSharp.DOMWorld.EvaluateExpressionAsync[T](String script)
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__Login|2>d.MoveNext() in /home/runner/work/Note[16](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:17)3Checkin/Note1[63](https://github.com/StoneForests/Note163Checkin/actions/runs/6446249117/job/17501173334#step:3:64)Checkin/Program.cs:line 169
login获取cookie,状态:无效
账号 1: youdao github action Cookie失效，请检查登录状态！
签到运行完毕
/usr/bin/bash /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh
/usr/bin/bash: /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh: No such file or directory
```

**Comment by BlueHtml** [comment]
@StoneForests 最新有道云登录页面添加了**滑块验证**，简单尝试后发现破解难度很大。
我这边是先用安卓端的cookie更新到redis里给action用了。
你也可以用手动登录网页端，然后获取cookie后手动更新到redis里。
![image](https://github.com/BlueHtml/Note163Checkin/assets/17940898/a0b9e0eb-466b-46ab-91e8-92c92bf1152f)

**Comment by StoneForests** [comment]
> @StoneForests 最新有道云登录页面添加了**滑块验证**，简单尝试后发现破解难度很大。 我这边是先用安卓端的cookie更新到redis里给action用了。 你也可以用手动登录网页端，然后获取cookie后手动更新到redis里。 [![image](https://user-images.githubusercontent.com/17940898/273593506-a0b9e0eb-466b-46ab-91e8-92c92bf1152f.png)](javascript:void(0))

感谢！我目前也是用的网页端的cookie塞到redis里使用的，但好像只有一周还是一个月的有效期。。你使用安卓端的cookie有效期有多久呢，用小黄鸟抓的么，关键字是啥？

**Comment by BlueHtml** [comment]
@StoneForests 安卓端的cookie有效期是**一周**。不过我现在换成网页端的cookie了，因为网页端我每天都在登录使用，想看下这种情况下它的有效期是多久，来决定后续怎么做

**Comment by BigBigBIgMan** [comment]
> @StoneForests 安卓端的cookie有效期是**一周**。不过我现在换成网页端的cookie了，因为网页端我每天都在登录使用，想看下这种情况下它的有效期是多久，来决定后续怎么做

我一直在用网页版的cookie,有效期也是一周

**Comment by BigBigBIgMan** [comment]
> @StoneForests 安卓端的cookie有效期是**一周**。不过我现在换成网页端的cookie了，因为网页端我每天都在登录使用，想看下这种情况下它的有效期是多久，来决定后续怎么做

我一直在用网页版的cookie,有效期也是一周（不过每次新打开网页会自动刷新cookie，不用登录）

**Comment by BlueHtml** [comment]
@BigBigBIgMan 对的，我也换成了网页版的cookie，2023-10-14更新的，现在(2023-11-4)还是有效的。不过前提是得每天都打开网页端进行使用，好像cookie会自动续期。

**Comment by jinde98** [comment]
![image](https://github.com/BlueHtml/Note163Checkin/assets/127750182/f63ddc94-2e3f-4e02-b25b-99999e08d458)
这一堆里面 哪个是需要的cookie啊
