### ISSUE TITLE
检查下添加的Secret的文件名称是否正确

### ISSUE THREAD

**Issue by zhoudahong** [BlueHtml/Note163Checkin#18]
检查下添加的Secret的文件名称是否正确

_Originally posted by @BigBigBIgMan in https://github.com/BlueHtml/Note163Checkin/issues/8#issuecomment-1524736686_

检查了配置名是Conf，登陆没问题，redis也更新了。但是还是会报以下错误。能烦请您解决一下吗，谢谢
Unhandled exception. PuppeteerSharp.NavigationException: Timeout of 60000 ms exceeded
 ---> System.TimeoutException: Timeout of 60000 ms exceeded
   at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 48
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 93
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 79
   --- End of inner exception stack trace ---
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 89
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__GetCookie|1>d.MoveNext() in /home/runner/work/Note163Checkin/Note163Checkin/Program.cs:line [117](https://github.com/zhoudahong/Note163Checkin/actions/runs/6268663092/job/17031087436#step:3:118)
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in /home/runner/work/Note163Checkin/Note163Checkin/Program.cs:line 46
   at Program.<Main>(String[] args)
/usr/bin/bash /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh
/usr/bin/bash: /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh: No such file or directory
Error: The process '/usr/bin/xvfb-run' failed with exit code 134

**Comment by BigBigBIgMan** [comment]
> ```
>           检查下添加的Secret的文件名称是否正确
> ```
> 
> _Originally posted by @BigBigBIgMan in [#8 (comment)](https://github.com/BlueHtml/Note163Checkin/issues/8#issuecomment-1524736686)_
> 
> 检查了配置名是Conf，登陆没问题，redis也更新了。但是还是会报以下错误。能烦请您解决一下吗，谢谢 Unhandled exception. PuppeteerSharp.NavigationException: Timeout of 60000 ms exceeded ---> System.TimeoutException: Timeout of 60000 ms exceeded at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.b__0() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 48 at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 93 at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 79 --- End of inner exception stack trace --- at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 89 at Program.<>c__DisplayClass0_0.<<
> 
> $>g__GetCookie|1>d.MoveNext() in /home/runner/work/Note163Checkin/Note163Checkin/Program.cs:line [117](https://github.com/zhoudahong/Note163Checkin/actions/runs/6268663092/job/17031087436#step:3:118)
> --- End of stack trace from previous location ---
> at Program.$(String[] args) in /home/runner/work/Note163Checkin/Note163Checkin/Program.cs:line 46
> at Program.(String[] args)
> /usr/bin/bash /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh
> /usr/bin/bash: /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh: No such file or directory
> Error: The process '/usr/bin/xvfb-run' failed with exit code 134

连接超时，只有偶尔才这样吧，这个是正常现象吧，你可以看作者的运行记录，也是会偶尔会超时的

**Comment by ichobits** [comment]
/usr/bin/xvfb-run --auto-servernum dotnet run
Unhandled exception. System.Text.Json.JsonException: '"' is invalid after a value. Expected either ',', '***', or ']'. Path: $ | LineNumber: 11 | BytePositionInLine: 1.
 ---> System.Text.Json.JsonReaderException: '"' is invalid after a value. Expected either ',', '***', or ']'. LineNumber: 11 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at Program.<<Main>$>g__Deserialize|0_5[T](String json) in /home/runner/work/Note1[63](https://github.com/ichobits/Note163Checkin_v2/actions/runs/8106182208/job/22155682356#step:3:64)Checkin_v2/Note163Checkin_v2/Program.cs:line 199
   at Program.<Main>$(String[] args) in /home/runner/work/Note163Checkin_v2/Note163Checkin_v2/Program.cs:line 8
   at Program.<Main>(String[] args)
/usr/bin/bash /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh
/usr/bin/bash: /home/runner/work/_actions/coactions/setup-xvfb/main/dist/cleanup.sh: No such file or directory
Error: The process '/usr/bin/xvfb-run' failed with exit code 134

=======================================
Secret设置的文件名为Conf与代码中的第13行一致，但是无法正确运行。始终报错

配置RdsServer
"RdsPwd"
但是ScKey是不是Access Management下的
API account key ，还是 API user keys ？
