### ISSUE TITLE
Login时出现异常

### ISSUE THREAD

**Issue by xapwv** [BlueHtml/Note163Checkin#19]
Login时出现异常！Evaluation failed: TypeError: Cannot read properties of null (reading 'querySelector')
    at main (__puppeteer_evaluation_script__:8:44)
    at __puppeteer_evaluation_script__:16:1.    at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 179
   at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 146
   at PuppeteerSharp.DOMWorld.EvaluateExpressionAsync[T](String script)
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__Login|2>d.MoveNext() in /home/runner/work/Note163Checkin/Note163Checkin/Program.cs:line 169

**Comment by BlueHtml** [comment]
@xapwv 有道云登录页面添加了滑块验证，所以登录失败了。你可以手动登录网页端，然后获取cookie后手动更新到redis里。详见issues #17

**Comment by BlueHtml** [comment]
@xapwv 自动登录已修复，请同步最新代码

![image](https://github.com/BlueHtml/Note163Checkin/assets/17940898/a66c0cef-60d1-41e8-ae14-6a06731b18f7)
